// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: artifacts.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts(submission_id, kind, checksum, state)
VALUES ($1, $2, $3, $4)
RETURNING id, submission_id, kind, checksum, state, created_at, updated_at
`

type CreateArtifactParams struct {
	SubmissionID pgtype.UUID
	Kind         string
	Checksum     string
	State        string
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.SubmissionID,
		arg.Kind,
		arg.Checksum,
		arg.State,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Kind,
		&i.Checksum,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, submission_id, kind, checksum, state, created_at, updated_at FROM artifacts WHERE id = $1
`

func (q *Queries) GetArtifactByID(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByID, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Kind,
		&i.Checksum,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactBySubmissionKind = `-- name: GetArtifactBySubmissionKind :one
SELECT id, submission_id, kind, checksum, state, created_at, updated_at FROM artifacts WHERE submission_id = $1 AND kind = $2
`

type GetArtifactBySubmissionKindParams struct {
	SubmissionID pgtype.UUID
	Kind         string
}

func (q *Queries) GetArtifactBySubmissionKind(ctx context.Context, arg GetArtifactBySubmissionKindParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactBySubmissionKind, arg.SubmissionID, arg.Kind)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Kind,
		&i.Checksum,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactsByChecksum = `-- name: ListArtifactsByChecksum :many
SELECT id, submission_id, kind, checksum, state, created_at, updated_at FROM artifacts WHERE checksum = $1 ORDER BY created_at
`

func (q *Queries) ListArtifactsByChecksum(ctx context.Context, checksum string) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByChecksum, checksum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Kind,
			&i.Checksum,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByStateOlderThan = `-- name: ListArtifactsByStateOlderThan :many
SELECT id, submission_id, kind, checksum, state, created_at, updated_at FROM artifacts
WHERE state = $1 AND updated_at < $2
ORDER BY updated_at
`

type ListArtifactsByStateOlderThanParams struct {
	State     string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListArtifactsByStateOlderThan(ctx context.Context, arg ListArtifactsByStateOlderThanParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByStateOlderThan, arg.State, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Kind,
			&i.Checksum,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsBySubmission = `-- name: ListArtifactsBySubmission :many
SELECT id, submission_id, kind, checksum, state, created_at, updated_at FROM artifacts WHERE submission_id = $1 ORDER BY created_at
`

func (q *Queries) ListArtifactsBySubmission(ctx context.Context, submissionID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Kind,
			&i.Checksum,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArtifactState = `-- name: SetArtifactState :exec
UPDATE artifacts SET state = $1, updated_at = NOW() WHERE id = $2
`

type SetArtifactStateParams struct {
	State string
	ID    pgtype.UUID
}

func (q *Queries) SetArtifactState(ctx context.Context, arg SetArtifactStateParams) error {
	_, err := q.db.Exec(ctx, setArtifactState, arg.State, arg.ID)
	return err
}
