// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEntriesFiltered = `-- name: CountEntriesFiltered :one
SELECT COUNT(*)::bigint
FROM batch_entries be
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
WHERE ($1::text = '' OR be.trace ILIKE '%' || $1 || '%'
       OR be.rdfi ILIKE '%' || $1 || '%'
       OR be.receiver_name ILIKE '%' || $1 || '%'
       OR be.receiver_account ILIKE '%' || $1 || '%'
       OR s.filename ILIKE '%' || $1 || '%')
  AND ($2::date IS NULL OR bh.effective_date >= $2::date)
  AND ($3::date IS NULL OR bh.effective_date <= $3::date)
`

type CountEntriesFilteredParams struct {
	Column1 string
	Column2 pgtype.Date
	Column3 pgtype.Date
}

func (q *Queries) CountEntriesFiltered(ctx context.Context, arg CountEntriesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntriesFiltered, arg.Column1, arg.Column2, arg.Column3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countHeadersFiltered = `-- name: CountHeadersFiltered :one
SELECT COUNT(*)::bigint
FROM batch_headers bh
JOIN submissions s ON s.id = bh.submission_id
WHERE ($1::text = '' OR bh.company_name ILIKE '%' || $1 || '%'
       OR bh.customer_id ILIKE '%' || $1 || '%'
       OR bh.company_description ILIKE '%' || $1 || '%'
       OR s.filename ILIKE '%' || $1 || '%')
  AND ($2::date IS NULL OR bh.effective_date >= $2::date)
  AND ($3::date IS NULL OR bh.effective_date <= $3::date)
`

type CountHeadersFilteredParams struct {
	Column1 string
	Column2 pgtype.Date
	Column3 pgtype.Date
}

func (q *Queries) CountHeadersFiltered(ctx context.Context, arg CountHeadersFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHeadersFiltered, arg.Column1, arg.Column2, arg.Column3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBatchEntry = `-- name: CreateBatchEntry :one
INSERT INTO batch_entries(header_id, rdfi, receiver_name, receiver_account, amount, tran_code, trace)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, header_id, rdfi, receiver_name, receiver_account, amount, tran_code, trace, created_at, updated_at
`

type CreateBatchEntryParams struct {
	HeaderID        pgtype.UUID
	Rdfi            string
	ReceiverName    string
	ReceiverAccount string
	Amount          int64
	TranCode        int32
	Trace           string
}

func (q *Queries) CreateBatchEntry(ctx context.Context, arg CreateBatchEntryParams) (BatchEntry, error) {
	row := q.db.QueryRow(ctx, createBatchEntry,
		arg.HeaderID,
		arg.Rdfi,
		arg.ReceiverName,
		arg.ReceiverAccount,
		arg.Amount,
		arg.TranCode,
		arg.Trace,
	)
	var i BatchEntry
	err := row.Scan(
		&i.ID,
		&i.HeaderID,
		&i.Rdfi,
		&i.ReceiverName,
		&i.ReceiverAccount,
		&i.Amount,
		&i.TranCode,
		&i.Trace,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBatchHeader = `-- name: CreateBatchHeader :one
INSERT INTO batch_headers(submission_id, customer_id, company_name, company_description, effective_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, submission_id, customer_id, company_name, company_description, effective_date, created_at, updated_at
`

type CreateBatchHeaderParams struct {
	SubmissionID       pgtype.UUID
	CustomerID         string
	CompanyName        string
	CompanyDescription string
	EffectiveDate      pgtype.Date
}

func (q *Queries) CreateBatchHeader(ctx context.Context, arg CreateBatchHeaderParams) (BatchHeader, error) {
	row := q.db.QueryRow(ctx, createBatchHeader,
		arg.SubmissionID,
		arg.CustomerID,
		arg.CompanyName,
		arg.CompanyDescription,
		arg.EffectiveDate,
	)
	var i BatchHeader
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.CustomerID,
		&i.CompanyName,
		&i.CompanyDescription,
		&i.EffectiveDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasEntryByRdfiAccount = `-- name: HasEntryByRdfiAccount :one
SELECT EXISTS(
    SELECT 1 FROM batch_entries
    WHERE rdfi = $1 AND receiver_account = $2
) AS "exists"
`

type HasEntryByRdfiAccountParams struct {
	Rdfi            string
	ReceiverAccount string
}

func (q *Queries) HasEntryByRdfiAccount(ctx context.Context, arg HasEntryByRdfiAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasEntryByRdfiAccount, arg.Rdfi, arg.ReceiverAccount)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEntriesBySubmission = `-- name: ListEntriesBySubmission :many
SELECT be.id, be.header_id, be.rdfi, be.receiver_name, be.receiver_account, be.amount, be.tran_code, be.trace, be.created_at, be.updated_at, bh.customer_id, bh.effective_date
FROM batch_entries be
JOIN batch_headers bh ON bh.id = be.header_id
WHERE bh.submission_id = $1
ORDER BY be.created_at
`

type ListEntriesBySubmissionRow struct {
	ID              pgtype.UUID
	HeaderID        pgtype.UUID
	Rdfi            string
	ReceiverName    string
	ReceiverAccount string
	Amount          int64
	TranCode        int32
	Trace           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CustomerID      string
	EffectiveDate   pgtype.Date
}

func (q *Queries) ListEntriesBySubmission(ctx context.Context, submissionID pgtype.UUID) ([]ListEntriesBySubmissionRow, error) {
	rows, err := q.db.Query(ctx, listEntriesBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesBySubmissionRow
	for rows.Next() {
		var i ListEntriesBySubmissionRow
		if err := rows.Scan(
			&i.ID,
			&i.HeaderID,
			&i.Rdfi,
			&i.ReceiverName,
			&i.ReceiverAccount,
			&i.Amount,
			&i.TranCode,
			&i.Trace,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.EffectiveDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesFiltered = `-- name: ListEntriesFiltered :many
SELECT be.id, be.header_id, be.rdfi, be.receiver_name, be.receiver_account, be.amount, be.tran_code, be.trace, be.created_at, be.updated_at, bh.customer_id, bh.effective_date, s.filename
FROM batch_entries be
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
WHERE ($1::text = '' OR be.trace ILIKE '%' || $1 || '%'
       OR be.rdfi ILIKE '%' || $1 || '%'
       OR be.receiver_name ILIKE '%' || $1 || '%'
       OR be.receiver_account ILIKE '%' || $1 || '%'
       OR s.filename ILIKE '%' || $1 || '%')
  AND ($2::date IS NULL OR bh.effective_date >= $2::date)
  AND ($3::date IS NULL OR bh.effective_date <= $3::date)
ORDER BY
  CASE WHEN $4::text = 'amount' AND $5::text = 'desc' THEN be.amount END DESC,
  CASE WHEN $4::text = 'amount' AND $5::text <> 'desc' THEN be.amount END ASC,
  CASE WHEN $4::text = 'tran_code' AND $5::text = 'desc' THEN be.tran_code END DESC,
  CASE WHEN $4::text = 'tran_code' AND $5::text <> 'desc' THEN be.tran_code END ASC,
  CASE WHEN $4::text = 'trace' AND $5::text = 'desc' THEN be.trace END DESC,
  CASE WHEN $4::text = 'trace' AND $5::text <> 'desc' THEN be.trace END ASC,
  CASE WHEN $4::text = 'rdfi' AND $5::text = 'desc' THEN be.rdfi END DESC,
  CASE WHEN $4::text = 'rdfi' AND $5::text <> 'desc' THEN be.rdfi END ASC,
  CASE WHEN $4::text = 'receiver' AND $5::text = 'desc' THEN be.receiver_name END DESC,
  CASE WHEN $4::text = 'receiver' AND $5::text <> 'desc' THEN be.receiver_name END ASC,
  CASE WHEN $4::text = 'account' AND $5::text = 'desc' THEN be.receiver_account END DESC,
  CASE WHEN $4::text = 'account' AND $5::text <> 'desc' THEN be.receiver_account END ASC,
  CASE WHEN $4::text = 'effective' AND $5::text = 'desc' THEN bh.effective_date END DESC,
  CASE WHEN $4::text = 'effective' AND $5::text <> 'desc' THEN bh.effective_date END ASC,
  CASE WHEN $4::text = 'filename' AND $5::text = 'desc' THEN s.filename END DESC,
  CASE WHEN $4::text = 'filename' AND $5::text <> 'desc' THEN s.filename END ASC,
  be.created_at DESC,
  be.id DESC
LIMIT $6 OFFSET $7
`

type ListEntriesFilteredParams struct {
	Column1 string
	Column2 pgtype.Date
	Column3 pgtype.Date
	Column4 string
	Column5 string
	Limit   int32
	Offset  int32
}

type ListEntriesFilteredRow struct {
	ID              pgtype.UUID
	HeaderID        pgtype.UUID
	Rdfi            string
	ReceiverName    string
	ReceiverAccount string
	Amount          int64
	TranCode        int32
	Trace           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CustomerID      string
	EffectiveDate   pgtype.Date
	Filename        string
}

func (q *Queries) ListEntriesFiltered(ctx context.Context, arg ListEntriesFilteredParams) ([]ListEntriesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listEntriesFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesFilteredRow
	for rows.Next() {
		var i ListEntriesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.HeaderID,
			&i.Rdfi,
			&i.ReceiverName,
			&i.ReceiverAccount,
			&i.Amount,
			&i.TranCode,
			&i.Trace,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.EffectiveDate,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeadersFiltered = `-- name: ListHeadersFiltered :many
SELECT bh.id, bh.submission_id, bh.customer_id, bh.company_name, bh.company_description, bh.effective_date, bh.created_at, bh.updated_at, s.filename
FROM batch_headers bh
JOIN submissions s ON s.id = bh.submission_id
WHERE ($1::text = '' OR bh.company_name ILIKE '%' || $1 || '%'
       OR bh.customer_id ILIKE '%' || $1 || '%'
       OR bh.company_description ILIKE '%' || $1 || '%'
       OR s.filename ILIKE '%' || $1 || '%')
  AND ($2::date IS NULL OR bh.effective_date >= $2::date)
  AND ($3::date IS NULL OR bh.effective_date <= $3::date)
ORDER BY
  CASE WHEN $4::text = 'company_name' AND $5::text = 'desc' THEN bh.company_name END DESC,
  CASE WHEN $4::text = 'company_name' AND $5::text <> 'desc' THEN bh.company_name END ASC,
  CASE WHEN $4::text = 'customer_id' AND $5::text = 'desc' THEN bh.customer_id END DESC,
  CASE WHEN $4::text = 'customer_id' AND $5::text <> 'desc' THEN bh.customer_id END ASC,
  CASE WHEN $4::text = 'effective' AND $5::text = 'desc' THEN bh.effective_date END DESC,
  CASE WHEN $4::text = 'effective' AND $5::text <> 'desc' THEN bh.effective_date END ASC,
  CASE WHEN $4::text = 'filename' AND $5::text = 'desc' THEN s.filename END DESC,
  CASE WHEN $4::text = 'filename' AND $5::text <> 'desc' THEN s.filename END ASC,
  bh.created_at DESC,
  bh.id DESC
LIMIT $6 OFFSET $7
`

type ListHeadersFilteredParams struct {
	Column1 string
	Column2 pgtype.Date
	Column3 pgtype.Date
	Column4 string
	Column5 string
	Limit   int32
	Offset  int32
}

type ListHeadersFilteredRow struct {
	ID                 pgtype.UUID
	SubmissionID       pgtype.UUID
	CustomerID         string
	CompanyName        string
	CompanyDescription string
	EffectiveDate      pgtype.Date
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Filename           string
}

func (q *Queries) ListHeadersFiltered(ctx context.Context, arg ListHeadersFilteredParams) ([]ListHeadersFilteredRow, error) {
	rows, err := q.db.Query(ctx, listHeadersFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeadersFilteredRow
	for rows.Next() {
		var i ListHeadersFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.CustomerID,
			&i.CompanyName,
			&i.CompanyDescription,
			&i.EffectiveDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumVelocity = `-- name: SumVelocity :many
WITH target_groups AS (
    SELECT DISTINCT be2.receiver_account, be2.rdfi, bh2.effective_date, bh2.customer_id
    FROM batch_entries be2
    JOIN batch_headers bh2 ON bh2.id = be2.header_id
    WHERE bh2.submission_id = $2
      AND be2.tran_code IN (22, 32)
      AND bh2.effective_date >= $1::date
)
SELECT be.receiver_account, be.rdfi, bh.effective_date, bh.customer_id,
       SUM(be.amount)::bigint AS total
FROM batch_entries be
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
JOIN target_groups tg
  ON tg.receiver_account = be.receiver_account
 AND tg.rdfi = be.rdfi
 AND tg.effective_date = bh.effective_date
 AND tg.customer_id = bh.customer_id
WHERE s.status IN ('ready', 'archived')
  AND be.tran_code IN (22, 32)
  AND bh.effective_date >= $1::date
  AND NOT EXISTS (
    -- A submission whose process job failed never built (or shipped) an
    -- intercept, so its entries are not real same-day exposure. This is
    -- self-healing: requeuing the process job includes it again.
    SELECT 1 FROM jobs j
    WHERE j.kind = 'process' AND j.ref = s.id AND j.state = 'failed'
  )
GROUP BY be.receiver_account, be.rdfi, bh.effective_date, bh.customer_id
`

type SumVelocityParams struct {
	Column1      pgtype.Date
	SubmissionID pgtype.UUID
}

type SumVelocityRow struct {
	ReceiverAccount string
	Rdfi            string
	EffectiveDate   pgtype.Date
	CustomerID      string
	Total           int64
}

// Same-day velocity per receiver account/RDFI/date/customer, summed across all
// ready submissions but restricted to the velocity groups that appear in the
// submission being screened, so the work is proportional to one file rather
// than the whole day.
func (q *Queries) SumVelocity(ctx context.Context, arg SumVelocityParams) ([]SumVelocityRow, error) {
	rows, err := q.db.Query(ctx, sumVelocity, arg.Column1, arg.SubmissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumVelocityRow
	for rows.Next() {
		var i SumVelocityRow
		if err := rows.Scan(
			&i.ReceiverAccount,
			&i.Rdfi,
			&i.EffectiveDate,
			&i.CustomerID,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
