// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holds.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHoldsByStatus = `-- name: CountHoldsByStatus :many
SELECT h.status, COUNT(*)::bigint AS count
FROM holds h
WHERE h.status = 'pending' OR h.updated_at >= $1::timestamptz
GROUP BY h.status
ORDER BY h.status
`

type CountHoldsByStatusRow struct {
	Status string
	Count  int64
}

// Open pending holds (the live review queue) always count, because they are the
// call to action; resolved statuses count only when decided since the cutoff,
// so the dashboard shows current pending alongside 7-day activity.
func (q *Queries) CountHoldsByStatus(ctx context.Context, dollar_1 pgtype.Timestamptz) ([]CountHoldsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countHoldsByStatus, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountHoldsByStatusRow
	for rows.Next() {
		var i CountHoldsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countHoldsFiltered = `-- name: CountHoldsFiltered :one
SELECT COUNT(*)::bigint
FROM holds h
JOIN batch_entries be ON be.id = h.entry_id
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
WHERE ($1::text = '' OR h.status = $1)
  AND ($2::text = '' OR s.filename ILIKE '%' || $2 || '%'
       OR be.receiver_name ILIKE '%' || $2 || '%'
       OR be.receiver_account ILIKE '%' || $2 || '%'
       OR be.trace ILIKE '%' || $2 || '%')
  AND ($3::date IS NULL OR bh.effective_date >= $3::date)
  AND ($4::date IS NULL OR bh.effective_date <= $4::date)
`

type CountHoldsFilteredParams struct {
	Column1 string
	Column2 string
	Column3 pgtype.Date
	Column4 pgtype.Date
}

func (q *Queries) CountHoldsFiltered(ctx context.Context, arg CountHoldsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHoldsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createHold = `-- name: CreateHold :one
INSERT INTO holds(entry_id, status, reason)
VALUES ($1, $2, $3)
RETURNING id, entry_id, status, release_artifact_id, created_at, updated_at, reason
`

type CreateHoldParams struct {
	EntryID pgtype.UUID
	Status  string
	Reason  string
}

func (q *Queries) CreateHold(ctx context.Context, arg CreateHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, createHold, arg.EntryID, arg.Status, arg.Reason)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Status,
		&i.ReleaseArtifactID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reason,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews(hold_id, actor, action, note)
VALUES ($1, $2, $3, $4)
RETURNING id, hold_id, actor, action, note, created_at
`

type CreateReviewParams struct {
	HoldID pgtype.UUID
	Actor  string
	Action string
	Note   string
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.HoldID,
		arg.Actor,
		arg.Action,
		arg.Note,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.HoldID,
		&i.Actor,
		&i.Action,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getHoldByID = `-- name: GetHoldByID :one
SELECT h.id, h.entry_id, h.status, h.release_artifact_id, h.created_at, h.updated_at, h.reason, be.trace AS entry_trace, be.rdfi AS entry_rdfi,
       be.receiver_name AS entry_receiver_name,
       be.receiver_account AS entry_receiver_account,
       be.amount AS entry_amount, be.tran_code AS entry_tran_code,
       bh.effective_date, bh.submission_id, bh.customer_id, bh.company_name,
       s.filename
FROM holds h
JOIN batch_entries be ON be.id = h.entry_id
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
WHERE h.id = $1
`

type GetHoldByIDRow struct {
	ID                   pgtype.UUID
	EntryID              pgtype.UUID
	Status               string
	ReleaseArtifactID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Reason               string
	EntryTrace           string
	EntryRdfi            string
	EntryReceiverName    string
	EntryReceiverAccount string
	EntryAmount          int64
	EntryTranCode        int32
	EffectiveDate        pgtype.Date
	SubmissionID         pgtype.UUID
	CustomerID           string
	CompanyName          string
	Filename             string
}

func (q *Queries) GetHoldByID(ctx context.Context, id pgtype.UUID) (GetHoldByIDRow, error) {
	row := q.db.QueryRow(ctx, getHoldByID, id)
	var i GetHoldByIDRow
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Status,
		&i.ReleaseArtifactID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reason,
		&i.EntryTrace,
		&i.EntryRdfi,
		&i.EntryReceiverName,
		&i.EntryReceiverAccount,
		&i.EntryAmount,
		&i.EntryTranCode,
		&i.EffectiveDate,
		&i.SubmissionID,
		&i.CustomerID,
		&i.CompanyName,
		&i.Filename,
	)
	return i, err
}

const listAllHolds = `-- name: ListAllHolds :many
SELECT h.id, h.entry_id, h.status, h.release_artifact_id, h.created_at, h.updated_at, h.reason, be.trace AS entry_trace, be.rdfi AS entry_rdfi,
       be.receiver_name AS entry_receiver_name,
       be.receiver_account AS entry_receiver_account,
       be.amount AS entry_amount, be.tran_code AS entry_tran_code,
       bh.effective_date, bh.submission_id, bh.customer_id, bh.company_name,
       s.filename
FROM holds h
JOIN batch_entries be ON be.id = h.entry_id
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
ORDER BY h.created_at
`

type ListAllHoldsRow struct {
	ID                   pgtype.UUID
	EntryID              pgtype.UUID
	Status               string
	ReleaseArtifactID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Reason               string
	EntryTrace           string
	EntryRdfi            string
	EntryReceiverName    string
	EntryReceiverAccount string
	EntryAmount          int64
	EntryTranCode        int32
	EffectiveDate        pgtype.Date
	SubmissionID         pgtype.UUID
	CustomerID           string
	CompanyName          string
	Filename             string
}

func (q *Queries) ListAllHolds(ctx context.Context) ([]ListAllHoldsRow, error) {
	rows, err := q.db.Query(ctx, listAllHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllHoldsRow
	for rows.Next() {
		var i ListAllHoldsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Status,
			&i.ReleaseArtifactID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reason,
			&i.EntryTrace,
			&i.EntryRdfi,
			&i.EntryReceiverName,
			&i.EntryReceiverAccount,
			&i.EntryAmount,
			&i.EntryTranCode,
			&i.EffectiveDate,
			&i.SubmissionID,
			&i.CustomerID,
			&i.CompanyName,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombosBySubmission = `-- name: ListCombosBySubmission :many
WITH my_combos AS (
    SELECT DISTINCT be.rdfi, be.receiver_account
    FROM batch_entries be
    JOIN batch_headers bh ON bh.id = be.header_id
    WHERE bh.submission_id = $1
      AND be.tran_code IN (22, 32)
      AND bh.effective_date >= $2::date
)
SELECT mc.rdfi, mc.receiver_account,
       EXISTS (
           SELECT 1 FROM holds h
           JOIN batch_entries be2 ON be2.id = h.entry_id
           WHERE be2.rdfi = mc.rdfi AND be2.receiver_account = mc.receiver_account
             AND h.status = 'approved'
       ) AS has_approved,
       EXISTS (
           SELECT 1 FROM holds h
           JOIN batch_entries be2 ON be2.id = h.entry_id
           WHERE be2.rdfi = mc.rdfi AND be2.receiver_account = mc.receiver_account
             AND h.status = 'declined'
       ) AS has_declined
FROM my_combos mc
`

type ListCombosBySubmissionParams struct {
	SubmissionID pgtype.UUID
	Column2      pgtype.Date
}

type ListCombosBySubmissionRow struct {
	Rdfi            string
	ReceiverAccount string
	HasApproved     bool
	HasDeclined     bool
}

// Whitelist/blacklist status for the receiver account/RDFI pairs present in the
// submission being screened. Full hold history (no expiry) is consulted via the
// EXISTS subqueries, but only for the pairs that matter to this file. A combo
// is whitelisted by a prior APPROVED hold and blacklisted by a prior DECLINED
// hold; pending/auto_declined holds count for neither (undecided, re-screened).
func (q *Queries) ListCombosBySubmission(ctx context.Context, arg ListCombosBySubmissionParams) ([]ListCombosBySubmissionRow, error) {
	rows, err := q.db.Query(ctx, listCombosBySubmission, arg.SubmissionID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCombosBySubmissionRow
	for rows.Next() {
		var i ListCombosBySubmissionRow
		if err := rows.Scan(
			&i.Rdfi,
			&i.ReceiverAccount,
			&i.HasApproved,
			&i.HasDeclined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldsByReleaseArtifact = `-- name: ListHoldsByReleaseArtifact :many
SELECT h.id, h.entry_id, h.status, h.release_artifact_id, h.created_at, h.updated_at, h.reason, be.trace AS entry_trace, be.rdfi AS entry_rdfi,
       be.receiver_name AS entry_receiver_name,
       be.receiver_account AS entry_receiver_account,
       be.amount AS entry_amount, be.tran_code AS entry_tran_code,
       bh.effective_date, bh.submission_id, bh.customer_id, bh.company_name,
       s.filename
FROM holds h
JOIN batch_entries be ON be.id = h.entry_id
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
WHERE h.release_artifact_id = $1
ORDER BY h.created_at
`

type ListHoldsByReleaseArtifactRow struct {
	ID                   pgtype.UUID
	EntryID              pgtype.UUID
	Status               string
	ReleaseArtifactID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Reason               string
	EntryTrace           string
	EntryRdfi            string
	EntryReceiverName    string
	EntryReceiverAccount string
	EntryAmount          int64
	EntryTranCode        int32
	EffectiveDate        pgtype.Date
	SubmissionID         pgtype.UUID
	CustomerID           string
	CompanyName          string
	Filename             string
}

func (q *Queries) ListHoldsByReleaseArtifact(ctx context.Context, releaseArtifactID pgtype.UUID) ([]ListHoldsByReleaseArtifactRow, error) {
	rows, err := q.db.Query(ctx, listHoldsByReleaseArtifact, releaseArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldsByReleaseArtifactRow
	for rows.Next() {
		var i ListHoldsByReleaseArtifactRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Status,
			&i.ReleaseArtifactID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reason,
			&i.EntryTrace,
			&i.EntryRdfi,
			&i.EntryReceiverName,
			&i.EntryReceiverAccount,
			&i.EntryAmount,
			&i.EntryTranCode,
			&i.EffectiveDate,
			&i.SubmissionID,
			&i.CustomerID,
			&i.CompanyName,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldsByStatus = `-- name: ListHoldsByStatus :many
SELECT h.id, h.entry_id, h.status, h.release_artifact_id, h.created_at, h.updated_at, h.reason, be.trace AS entry_trace, be.rdfi AS entry_rdfi,
       be.receiver_name AS entry_receiver_name,
       be.receiver_account AS entry_receiver_account,
       be.amount AS entry_amount, be.tran_code AS entry_tran_code,
       bh.effective_date, bh.submission_id, bh.customer_id, bh.company_name,
       s.filename
FROM holds h
JOIN batch_entries be ON be.id = h.entry_id
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
WHERE ($1::text = '' OR h.status = $1)
ORDER BY h.created_at DESC
LIMIT $2
`

type ListHoldsByStatusParams struct {
	Column1 string
	Limit   int32
}

type ListHoldsByStatusRow struct {
	ID                   pgtype.UUID
	EntryID              pgtype.UUID
	Status               string
	ReleaseArtifactID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Reason               string
	EntryTrace           string
	EntryRdfi            string
	EntryReceiverName    string
	EntryReceiverAccount string
	EntryAmount          int64
	EntryTranCode        int32
	EffectiveDate        pgtype.Date
	SubmissionID         pgtype.UUID
	CustomerID           string
	CompanyName          string
	Filename             string
}

func (q *Queries) ListHoldsByStatus(ctx context.Context, arg ListHoldsByStatusParams) ([]ListHoldsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listHoldsByStatus, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldsByStatusRow
	for rows.Next() {
		var i ListHoldsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Status,
			&i.ReleaseArtifactID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reason,
			&i.EntryTrace,
			&i.EntryRdfi,
			&i.EntryReceiverName,
			&i.EntryReceiverAccount,
			&i.EntryAmount,
			&i.EntryTranCode,
			&i.EffectiveDate,
			&i.SubmissionID,
			&i.CustomerID,
			&i.CompanyName,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldsBySubmission = `-- name: ListHoldsBySubmission :many
SELECT h.id, h.entry_id, h.status, h.release_artifact_id, h.created_at, h.updated_at, h.reason, be.trace AS entry_trace, be.rdfi AS entry_rdfi,
       be.receiver_name AS entry_receiver_name,
       be.receiver_account AS entry_receiver_account,
       be.amount AS entry_amount, be.tran_code AS entry_tran_code,
       bh.effective_date, bh.submission_id, bh.customer_id, bh.company_name,
       s.filename
FROM holds h
JOIN batch_entries be ON be.id = h.entry_id
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
WHERE bh.submission_id = $1
ORDER BY h.created_at
`

type ListHoldsBySubmissionRow struct {
	ID                   pgtype.UUID
	EntryID              pgtype.UUID
	Status               string
	ReleaseArtifactID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Reason               string
	EntryTrace           string
	EntryRdfi            string
	EntryReceiverName    string
	EntryReceiverAccount string
	EntryAmount          int64
	EntryTranCode        int32
	EffectiveDate        pgtype.Date
	SubmissionID         pgtype.UUID
	CustomerID           string
	CompanyName          string
	Filename             string
}

func (q *Queries) ListHoldsBySubmission(ctx context.Context, submissionID pgtype.UUID) ([]ListHoldsBySubmissionRow, error) {
	rows, err := q.db.Query(ctx, listHoldsBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldsBySubmissionRow
	for rows.Next() {
		var i ListHoldsBySubmissionRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Status,
			&i.ReleaseArtifactID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reason,
			&i.EntryTrace,
			&i.EntryRdfi,
			&i.EntryReceiverName,
			&i.EntryReceiverAccount,
			&i.EntryAmount,
			&i.EntryTranCode,
			&i.EffectiveDate,
			&i.SubmissionID,
			&i.CustomerID,
			&i.CompanyName,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldsFiltered = `-- name: ListHoldsFiltered :many
SELECT h.id, h.entry_id, h.status, h.release_artifact_id, h.created_at, h.updated_at, h.reason, be.trace AS entry_trace, be.rdfi AS entry_rdfi,
       be.receiver_name AS entry_receiver_name,
       be.receiver_account AS entry_receiver_account,
       be.amount AS entry_amount, be.tran_code AS entry_tran_code,
       bh.effective_date, bh.submission_id, bh.customer_id, bh.company_name,
       s.filename
FROM holds h
JOIN batch_entries be ON be.id = h.entry_id
JOIN batch_headers bh ON bh.id = be.header_id
JOIN submissions s ON s.id = bh.submission_id
WHERE ($1::text = '' OR h.status = $1)
  AND ($2::text = '' OR s.filename ILIKE '%' || $2 || '%'
       OR be.receiver_name ILIKE '%' || $2 || '%'
       OR be.receiver_account ILIKE '%' || $2 || '%'
       OR be.trace ILIKE '%' || $2 || '%')
  AND ($3::date IS NULL OR bh.effective_date >= $3::date)
  AND ($4::date IS NULL OR bh.effective_date <= $4::date)
ORDER BY
  CASE WHEN $5::text = 'amount' AND $6::text = 'desc' THEN be.amount END DESC,
  CASE WHEN $5::text = 'amount' AND $6::text <> 'desc' THEN be.amount END ASC,
  CASE WHEN $5::text = 'filename' AND $6::text = 'desc' THEN s.filename END DESC,
  CASE WHEN $5::text = 'filename' AND $6::text <> 'desc' THEN s.filename END ASC,
  CASE WHEN $5::text = 'effective' AND $6::text = 'desc' THEN bh.effective_date END DESC,
  CASE WHEN $5::text = 'effective' AND $6::text <> 'desc' THEN bh.effective_date END ASC,
  CASE WHEN $5::text = 'receiver' AND $6::text = 'desc' THEN be.receiver_name END DESC,
  CASE WHEN $5::text = 'receiver' AND $6::text <> 'desc' THEN be.receiver_name END ASC,
  CASE WHEN $5::text = 'account' AND $6::text = 'desc' THEN be.receiver_account END DESC,
  CASE WHEN $5::text = 'account' AND $6::text <> 'desc' THEN be.receiver_account END ASC,
  CASE WHEN $5::text = 'rdfi' AND $6::text = 'desc' THEN be.rdfi END DESC,
  CASE WHEN $5::text = 'rdfi' AND $6::text <> 'desc' THEN be.rdfi END ASC,
  CASE WHEN $5::text = 'customer' AND $6::text = 'desc' THEN bh.customer_id END DESC,
  CASE WHEN $5::text = 'customer' AND $6::text <> 'desc' THEN bh.customer_id END ASC,
  CASE WHEN $5::text = 'status' AND $6::text = 'desc' THEN h.status END DESC,
  CASE WHEN $5::text = 'status' AND $6::text <> 'desc' THEN h.status END ASC,
  h.created_at DESC,
  h.id DESC
LIMIT $7 OFFSET $8
`

type ListHoldsFilteredParams struct {
	Column1 string
	Column2 string
	Column3 pgtype.Date
	Column4 pgtype.Date
	Column5 string
	Column6 string
	Limit   int32
	Offset  int32
}

type ListHoldsFilteredRow struct {
	ID                   pgtype.UUID
	EntryID              pgtype.UUID
	Status               string
	ReleaseArtifactID    pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Reason               string
	EntryTrace           string
	EntryRdfi            string
	EntryReceiverName    string
	EntryReceiverAccount string
	EntryAmount          int64
	EntryTranCode        int32
	EffectiveDate        pgtype.Date
	SubmissionID         pgtype.UUID
	CustomerID           string
	CompanyName          string
	Filename             string
}

func (q *Queries) ListHoldsFiltered(ctx context.Context, arg ListHoldsFilteredParams) ([]ListHoldsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listHoldsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldsFilteredRow
	for rows.Next() {
		var i ListHoldsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Status,
			&i.ReleaseArtifactID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reason,
			&i.EntryTrace,
			&i.EntryRdfi,
			&i.EntryReceiverName,
			&i.EntryReceiverAccount,
			&i.EntryAmount,
			&i.EntryTranCode,
			&i.EffectiveDate,
			&i.SubmissionID,
			&i.CustomerID,
			&i.CompanyName,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByHold = `-- name: ListReviewsByHold :many
SELECT id, hold_id, actor, action, note, created_at FROM reviews WHERE hold_id = $1 ORDER BY created_at
`

func (q *Queries) ListReviewsByHold(ctx context.Context, holdID pgtype.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByHold, holdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.HoldID,
			&i.Actor,
			&i.Action,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHoldReleaseArtifact = `-- name: SetHoldReleaseArtifact :exec
UPDATE holds SET release_artifact_id = $1, updated_at = NOW() WHERE id = $2
`

type SetHoldReleaseArtifactParams struct {
	ReleaseArtifactID pgtype.UUID
	ID                pgtype.UUID
}

func (q *Queries) SetHoldReleaseArtifact(ctx context.Context, arg SetHoldReleaseArtifactParams) error {
	_, err := q.db.Exec(ctx, setHoldReleaseArtifact, arg.ReleaseArtifactID, arg.ID)
	return err
}

const setHoldStatus = `-- name: SetHoldStatus :exec
UPDATE holds SET status = $1, updated_at = NOW() WHERE id = $2
`

type SetHoldStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) SetHoldStatus(ctx context.Context, arg SetHoldStatusParams) error {
	_, err := q.db.Exec(ctx, setHoldStatus, arg.Status, arg.ID)
	return err
}

const setHoldStatusIfOpen = `-- name: SetHoldStatusIfOpen :one
UPDATE holds
SET status = $1, updated_at = NOW()
WHERE id = $2 AND status IN ('pending', 'auto_declined')
RETURNING id
`

type SetHoldStatusIfOpenParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) SetHoldStatusIfOpen(ctx context.Context, arg SetHoldStatusIfOpenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, setHoldStatusIfOpen, arg.Status, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
