// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: jobs.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireIngestLock = `-- name: AcquireIngestLock :one
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AcquireIngestLock(ctx context.Context, pgAdvisoryXactLock int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, acquireIngestLock, pgAdvisoryXactLock)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const claimDueJob = `-- name: ClaimDueJob :one
UPDATE jobs SET state = 'in_progress', updated_at = NOW()
WHERE id = (
    SELECT id FROM jobs
    WHERE state = 'queued' AND run_at <= NOW()
    ORDER BY run_at, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, ref, state, failures, last_error, run_at, created_at, updated_at
`

func (q *Queries) ClaimDueJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimDueJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Ref,
		&i.State,
		&i.Failures,
		&i.LastError,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs SET state = 'done', updated_at = NOW() WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :exec
INSERT INTO jobs(kind, ref, state, run_at)
VALUES ($1, $2, 'queued', $3)
ON CONFLICT (kind, ref) DO UPDATE
SET run_at = $3, state = 'queued', updated_at = NOW()
`

type EnqueueJobParams struct {
	Kind  string
	Ref   pgtype.UUID
	RunAt pgtype.Timestamptz
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.Exec(ctx, enqueueJob, arg.Kind, arg.Ref, arg.RunAt)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET state = 'failed', failures = failures + 1,
    last_error = $2, updated_at = NOW()
WHERE id = $1
`

type FailJobParams struct {
	ID        pgtype.UUID
	LastError string
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.LastError)
	return err
}

const listJobsByRef = `-- name: ListJobsByRef :many
SELECT id, kind, ref, state, failures, last_error, run_at, created_at, updated_at FROM jobs WHERE ref = $1 ORDER BY created_at
`

func (q *Queries) ListJobsByRef(ctx context.Context, ref pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRef, ref)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Ref,
			&i.State,
			&i.Failures,
			&i.LastError,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByState = `-- name: ListJobsByState :many
SELECT id, kind, ref, state, failures, last_error, run_at, created_at, updated_at FROM jobs WHERE state = $1 ORDER BY run_at LIMIT $2
`

type ListJobsByStateParams struct {
	State string
	Limit int32
}

func (q *Queries) ListJobsByState(ctx context.Context, arg ListJobsByStateParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByState, arg.State, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Ref,
			&i.State,
			&i.Failures,
			&i.LastError,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueJob = `-- name: RequeueJob :one
UPDATE jobs
SET state = 'queued', run_at = NOW(), last_error = '', updated_at = NOW()
WHERE id = $1
RETURNING id, kind, ref, state, failures, last_error, run_at, created_at, updated_at
`

func (q *Queries) RequeueJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, requeueJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Ref,
		&i.State,
		&i.Failures,
		&i.LastError,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :exec
UPDATE jobs SET state = 'queued', updated_at = NOW()
WHERE state = 'in_progress' AND updated_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) RequeueStaleJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, requeueStaleJobs)
	return err
}
