// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID           pgtype.UUID
	SubmissionID pgtype.UUID
	Kind         string
	Checksum     string
	State        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type BatchEntry struct {
	ID              pgtype.UUID
	HeaderID        pgtype.UUID
	Rdfi            string
	ReceiverName    string
	ReceiverAccount string
	Amount          int64
	TranCode        int32
	Trace           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type BatchHeader struct {
	ID                 pgtype.UUID
	SubmissionID       pgtype.UUID
	CustomerID         string
	CompanyName        string
	CompanyDescription string
	EffectiveDate      pgtype.Date
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Event struct {
	ID        pgtype.UUID
	Type      string
	Ref       pgtype.UUID
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type Hold struct {
	ID                pgtype.UUID
	EntryID           pgtype.UUID
	Status            string
	ReleaseArtifactID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Reason            string
}

type Job struct {
	ID        pgtype.UUID
	Kind      string
	Ref       pgtype.UUID
	State     string
	Failures  int32
	LastError string
	RunAt     pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Review struct {
	ID        pgtype.UUID
	HoldID    pgtype.UUID
	Actor     string
	Action    string
	Note      string
	CreatedAt pgtype.Timestamptz
}

type Submission struct {
	ID             pgtype.UUID
	Filename       string
	SourceChecksum string
	Status         string
	FailedReason   string
	ReceivedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
