// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipients.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRecipientAlert = `-- name: AddRecipientAlert :exec
INSERT INTO recipient_alerts(recipient_id, alert_type)
VALUES ($1, $2)
`

type AddRecipientAlertParams struct {
	RecipientID pgtype.UUID
	AlertType   string
}

func (q *Queries) AddRecipientAlert(ctx context.Context, arg AddRecipientAlertParams) error {
	_, err := q.db.Exec(ctx, addRecipientAlert, arg.RecipientID, arg.AlertType)
	return err
}

const clearRecipientAlerts = `-- name: ClearRecipientAlerts :exec
DELETE FROM recipient_alerts WHERE recipient_id = $1
`

func (q *Queries) ClearRecipientAlerts(ctx context.Context, recipientID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRecipientAlerts, recipientID)
	return err
}

const createRecipient = `-- name: CreateRecipient :one
INSERT INTO recipients(email, name, enabled)
VALUES ($1, $2, $3)
RETURNING id, email, name, enabled, created_at
`

type CreateRecipientParams struct {
	Email   string
	Name    string
	Enabled bool
}

func (q *Queries) CreateRecipient(ctx context.Context, arg CreateRecipientParams) (Recipient, error) {
	row := q.db.QueryRow(ctx, createRecipient, arg.Email, arg.Name, arg.Enabled)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecipient = `-- name: DeleteRecipient :exec
DELETE FROM recipients WHERE id = $1
`

func (q *Queries) DeleteRecipient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipient, id)
	return err
}

const listRecipientAlerts = `-- name: ListRecipientAlerts :many
SELECT recipient_id, alert_type FROM recipient_alerts
`

func (q *Queries) ListRecipientAlerts(ctx context.Context) ([]RecipientAlert, error) {
	rows, err := q.db.Query(ctx, listRecipientAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipientAlert
	for rows.Next() {
		var i RecipientAlert
		if err := rows.Scan(&i.RecipientID, &i.AlertType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipients = `-- name: ListRecipients :many
SELECT id, email, name, enabled, created_at FROM recipients ORDER BY email
`

func (q *Queries) ListRecipients(ctx context.Context) ([]Recipient, error) {
	rows, err := q.db.Query(ctx, listRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipient
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipient = `-- name: UpdateRecipient :one
UPDATE recipients SET email = $1, name = $2, enabled = $3
 WHERE id = $4
RETURNING id, email, name, enabled, created_at
`

type UpdateRecipientParams struct {
	Email   string
	Name    string
	Enabled bool
	ID      pgtype.UUID
}

func (q *Queries) UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (Recipient, error) {
	row := q.db.QueryRow(ctx, updateRecipient,
		arg.Email,
		arg.Name,
		arg.Enabled,
		arg.ID,
	)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
