// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions(filename, source_checksum, status, received_at)
VALUES ($1, $2, $3, $4)
RETURNING id, filename, source_checksum, status, failed_reason, received_at, created_at, updated_at
`

type CreateSubmissionParams struct {
	Filename       string
	SourceChecksum string
	Status         string
	ReceivedAt     pgtype.Timestamptz
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.Filename,
		arg.SourceChecksum,
		arg.Status,
		arg.ReceivedAt,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.SourceChecksum,
		&i.Status,
		&i.FailedReason,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSubmissionsBySourceChecksum = `-- name: FindSubmissionsBySourceChecksum :many
SELECT id, filename, source_checksum, status, failed_reason, received_at, created_at, updated_at FROM submissions WHERE source_checksum = $1 ORDER BY received_at DESC
`

func (q *Queries) FindSubmissionsBySourceChecksum(ctx context.Context, sourceChecksum string) ([]Submission, error) {
	rows, err := q.db.Query(ctx, findSubmissionsBySourceChecksum, sourceChecksum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.SourceChecksum,
			&i.Status,
			&i.FailedReason,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, filename, source_checksum, status, failed_reason, received_at, created_at, updated_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id pgtype.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.SourceChecksum,
		&i.Status,
		&i.FailedReason,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReceivedWithoutFixJob = `-- name: ListReceivedWithoutFixJob :many
SELECT s.id, s.filename, s.source_checksum, s.status, s.failed_reason, s.received_at, s.created_at, s.updated_at FROM submissions s
WHERE s.status = 'received'
  AND NOT EXISTS (
    SELECT 1 FROM jobs j WHERE j.kind = 'fix_submission' AND j.ref = s.id
  )
`

func (q *Queries) ListReceivedWithoutFixJob(ctx context.Context) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listReceivedWithoutFixJob)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.SourceChecksum,
			&i.Status,
			&i.FailedReason,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, filename, source_checksum, status, failed_reason, received_at, created_at, updated_at FROM submissions
WHERE ($1::text = '' OR status = $1)
ORDER BY received_at DESC
LIMIT $2
`

type ListSubmissionsParams struct {
	Column1 string
	Limit   int32
}

func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissions, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.SourceChecksum,
			&i.Status,
			&i.FailedReason,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubmissionStatus = `-- name: SetSubmissionStatus :exec
UPDATE submissions
SET status = $1, failed_reason = $2, updated_at = NOW()
WHERE id = $3
`

type SetSubmissionStatusParams struct {
	Status       string
	FailedReason string
	ID           pgtype.UUID
}

func (q *Queries) SetSubmissionStatus(ctx context.Context, arg SetSubmissionStatusParams) error {
	_, err := q.db.Exec(ctx, setSubmissionStatus, arg.Status, arg.FailedReason, arg.ID)
	return err
}
