// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verifications.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVerificationBySubmission = `-- name: GetVerificationBySubmission :one
SELECT submission_id, verified, issues, checked_at FROM verifications WHERE submission_id = $1
`

func (q *Queries) GetVerificationBySubmission(ctx context.Context, submissionID pgtype.UUID) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationBySubmission, submissionID)
	var i Verification
	err := row.Scan(
		&i.SubmissionID,
		&i.Verified,
		&i.Issues,
		&i.CheckedAt,
	)
	return i, err
}

const upsertVerification = `-- name: UpsertVerification :one
INSERT INTO verifications(submission_id, verified, issues, checked_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (submission_id)
DO UPDATE SET verified = EXCLUDED.verified, issues = EXCLUDED.issues, checked_at = NOW()
RETURNING submission_id, verified, issues, checked_at
`

type UpsertVerificationParams struct {
	SubmissionID pgtype.UUID
	Verified     bool
	Issues       string
}

func (q *Queries) UpsertVerification(ctx context.Context, arg UpsertVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, upsertVerification, arg.SubmissionID, arg.Verified, arg.Issues)
	var i Verification
	err := row.Scan(
		&i.SubmissionID,
		&i.Verified,
		&i.Issues,
		&i.CheckedAt,
	)
	return i, err
}
